# FILE: _config.yml
# Memberitahu Jekyll dan Netlify cara membangun situs Anda

title: Pendakian Raviansyah
email: [GANTI DENGAN EMAIL ANDA]
description: 'Jurnal Pendakian dan Petualangan'
baseurl: ""
url: "https://[NAMA-SITUS-NETLIFY-ANDA].netlify.app" # Ganti dengan URL Netlify Anda
markdown: kramdown
permalink: /jurnal/:year/:month/:day/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - login.html 
  - admin.html 
  - dashboard-style.css
  - dashboard.js
  - admin/
